### ISSUE TITLE
command line repo-client kwargs error

### ISSUE THREAD

**Issue by molinaro-m** [opencadc/caom2tools#13]
caom2-repo-client throws this error:

Traceback (most recent call last):
  File "/bin/caom2-repo-client", line 9, in <module>
    load_entry_point('caom2repo==1.1.1', 'console_scripts', 'caom2-repo-client')()
  File "/usr/lib/python2.7/site-packages/caom2repo/core.py", line 383, in main
    client.put_observation(obs_reader.read(args.observation))
  File "/usr/lib/python2.7/site-packages/caom2repo/core.py", line 271, in put_observation
    resource, headers=headers, data=obs_xml)
  File "/usr/lib/python2.7/site-packages/cadcutils/net/ws.py", line 233, in put
    return self._get_session().put(self._get_url(resource), **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 528, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/cadcutils/net/ws.py", line 339, in send
    raise e

on a Fedora 24 (kernel 4.8.8-200.fc24.x86_64) with Python 2.7.12.

**Comment by andamian** [comment]
Not clear how to reproduce this.
